### ISSUE TITLE
Task /core: Experiment current structure with more plugins

### ISSUE THREAD

**Issue by webcrumbs-community** [webcrumbs-community/webcrumbs#163]
**What Needs to Be Done?**
Our need to test the existing structure of WebCrumbs (`experiment-5`) by integrating a variety of plugins. It isn't about adding new functionalities per se, but rather ensuring that our current setup is robust and versatile enough to handle different types of plugins efficiently.

**Why Is This Important?**
To ensure adaptability and scalability. It helps us identify potential areas of improvement and confirms our framework's readiness for a broader range of applications.

**Skills Needed**
- JavaScript
- React
- An analytical approach to testing and debugging
- Or simply a zest for exploring new plugin integrations!

**Requirements**
1. Copy the `experiment-5` to an `experiment-x` where `x` is the next available number.
1. Identify a range of plugins that test different aspects of WebCrumbs' structure.
2. Integrate these plugins into the existing WebCrumbs setup, focusing on compatibility and performance.
3. Conduct thorough testing to evaluate how well the current structure supports these varied plugins.
4. Document your findings in your experiment `README.md`, highlighting both successes and areas for potential improvement.

This task is an excellent way to contribute to the foundational strength of WebCrumbs. 
Your insights will be invaluable in shaping its future.

**Comment by webcrumbs-community** [comment]
Hi, @aditya4196! As we talked earlier today, I added the documentation on how to bundle plugins to the [README.md of experiment-5](https://github.com/webcrumbs-community/webcrumbs/blob/main/core/experiment-5/README.md). Let me know if you miss anything. Cheers!

**Comment by dew-dr0p** [comment]
Hi @webcrumbs-community would like to jump on this one.
Any other thing that might be of help?

**Comment by webcrumbs-community** [comment]
Hey, @dew-dr0p. Awesome! I'd suggest starting with the README.md file and studying the structure of the experiment-5 directory. We can set up a meeting if you prefer.

**Comment by webcrumbs-community** [comment]
Some questions for us to dig in. With this structure, can we have a plugin that handles upload of an image, conversion to PDF and download? Can we have some scheduled jobs? If not, is it achievable?

**Comment by dew-dr0p** [comment]
I've been able to work on a plugin that handles file upload, but while trying to work on file conversion, I came across and issue which leads to a question.

How do we handle external libraries, so let's say someone is building a plugin that uses external library how does that library get exposed to the admin or the application where the plugin would be used.

While I'll be trying to resolve this and answer the question, anyone with an idea on how this should work could just comment below so we could see. @aditya4196 @webcrumbs-community

**Comment by webcrumbs-community** [comment]
Good one, @dew-dr0p. Let's brainstorm a solution together.

I believe webpack tries to address that for the client side, but I can't remember right now on whether our implementation makes use of this.

For the server side rendering, I'm thinking that the registry should also serve some kind of json file listing the dependencies and versions, so that when we load a remote plugin we also make sure to load the dependencies if they are not yet cached.

What do you think?

**Comment by dew-dr0p** [comment]
I've already kind of worked on a solution, which is exactly what you mentioned @webcrumbs-community .

Currently each plugin (beginning from the new one I created, I'll update the template after) exposes a json file that list the necessary dependencies (I initially didn't add the versions but I'll include that now), and when the plugin is fetched from the admin panel, it gets that file and installs the missing dependency.

I also discovered something during the process, currently we're using a caching system (which I had to disable temporarily), we'll need a way to invalidate the cache after a while, so when plugins are being fetched, it wouldn't skip installing the missing dependencies.

Currently the only issue I'm facing is trying to isolate some of the plugin code to client side, because I'm facing some issues with the current SSR.

**Comment by dew-dr0p** [comment]
Hi @webcrumbs-community any other plugin idea, so I could add before I submit a PR?

**Comment by webcrumbs-community** [comment]
> Hi @webcrumbs-community any other plugin idea, so I could add before I submit a PR?

Hey, @dew-dr0p! Not for now, no. Thanks for asking. Those two seemed challenging enough and I can't wait to see your creative solutions in action. Looking forward to your PR!

**Comment by dew-dr0p** [comment]
@webcrumbs-community I've been facing an issue, since after building the plugin, this error came up unexpectedly and has since been the issue why I've not been able to submit my PR.
Basically, it has to do with webpack's code splitting. I'm dynamically importing the module that handles the file conversion into plugin's code (I had to go through this route as I was having issues with SSR, so I isolated the logic to run client side only and hence the reason for dynamically importing it at runtime).
The issue now is that, while trying to import the module, the browser throws an error about not being able to load the generated chunks (and when you inspect the network requests, it shows you that the chunks are fetched successfully).
I'm currently a bit confused now, but I'm really trying to get this sorted out as soon as I can, any help would be really appreciated.
I want to finish this quick, so I can pick up the Module Federation experiments we were trying, seems like I've been able to figure out some ways around it that I want to try.

**Comment by webcrumbs-community** [comment]
Hi @dew-dr0p. Do you want to share your fork with me so I can take a look?

**Comment by dew-dr0p** [comment]
Okay.
This is my fork
https://github.com/dew-dr0p/webcrumbs/tree/experiment-6

You can clone it and try to build experiment 6.
After building and starting the server, it should build out as expected, then when you try to open plugin3 (which is the new plugin). Check the browser console for the error.

There is a lot of commented codes (which I'll still clean up after resolving everything, I've also not edited the template yet)

**Comment by dew-dr0p** [comment]
> Okay. This is my fork https://github.com/dew-dr0p/webcrumbs/tree/experiment-6
> 
> You can clone it and try to build experiment 6. After building and starting the server, it should build out as expected, then when you try to open plugin3 (which is the new plugin). Check the browser console for the error.
> 
> There is a lot of commented codes (which I'll still clean up after resolving everything, I've also not edited the template yet)

We could get on a call whenever you're free to discuss this. @webcrumbs-community
